# Generated by Django 3.0.7 on 2020-07-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
