# Generated by Django 3.0.7 on 2020-07-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200712_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(blank=True, choices=[('US', 'User'), ('PR', 'Project Manager'), ('QA', 'Quality Analyst'), ('AD', 'Admin')], default='US', max_length=100, null=True),
        ),
    ]
