# Generated by Django 3.0.7 on 2020-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200715_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
